# Generated by Django 6.0.3 on 2026-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='original_image',
            field=models.FileField(blank=True, null=True, upload_to='original_uploads/'),
        ),
    ]
