# Generated by Django 6.0.3 on 2026-03-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imageupload_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
