# Generated by Django 6.0.3 on 2026-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_annotationrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationrow',
            name='category',
            field=models.CharField(choices=[('signboard', 'Signboard'), ('road', 'Road'), ('number_plate', 'Number plate')], max_length=32),
        ),
    ]
